curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-02-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-03-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-04-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-05-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-06-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-07-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-08-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-09-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-010-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-011-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-012-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-013-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-014-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-015-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-016-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-017-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-018-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-019-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-020-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-021-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-022-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-023-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-024-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-025-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-026-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-027-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-028-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-029-events.csv
curl -LJO http://raw.githubusercontent.com/san089/Udacity-Data-Engineering-Projects/master/Data_Modeling_with_Apache_Cassandra/event_data/2018-11-030-events.csv